/* ************************************************************************** */
/*                                                                            */
/*                                                        ::::::::            */
/*   main2.c                                            :+:    :+:            */
/*                                                     +:+                    */
/*   By: rbakker <rbakker@student.codam.nl>           +#+                     */
/*                                                   +#+                      */
/*   Created: 2019/12/20 11:34:35 by rbakker        #+#    #+#                */
/*   Updated: 2019/12/20 16:08:49 by rbakker       ########   odam.nl         */
/*                                                                            */
/* ************************************************************************** */

#include "ft_printf.h"

int main(void)
{
    int res_echte;
    int res_eigen;
	
    printf("echte =  [%-10c]\n", 'a');
    ft_printf("eigen =  [%-10c]\n", 'a');
    ft_printf("\n");
    printf("echte =  [%*c]\n", 10, 'a');
    ft_printf("eigen =  [%*c]\n", 10, 'a');
    ft_printf("\n");
    printf("echte =  [%-*c]\n", 10, 'a');
    ft_printf("eigen =  [%-*c]\n", 10, 'a');
    ft_printf("\n");
    printf("echte =  [%.*s]\n", 10, "abcde");
    ft_printf("eigen =  [%.*s]\n", 10, "abcde");
    ft_printf("\n");
    printf("echte =  [%.*s]\n", 4, "abcde");
    ft_printf("eigen =  [%.*s]\n", 4, "abcde");
    ft_printf("\n");
    printf("echte =  [%*s]\n", 4, "abcde");
    ft_printf("eigen =  [%*s]\n", 4, "abcde");
    ft_printf("\n");
    printf("echte =  [%10s]\n", "abcde");
    ft_printf("eigen =  [%10s]\n", "abcde");
    ft_printf("\n");
    res_echte = printf("de eerste is simpel");
    printf("  res = %d\n", res_echte);
    res_eigen = ft_printf("de eerste is simpel");
    printf("  res = %d\n", res_eigen);
    ft_printf("\n");
    res_echte = printf("Hello, world!");
    printf("  res = %d\n", res_echte);
    res_eigen = ft_printf("Hello, world!");
    printf("  res = %d\n", res_eigen);
    ft_printf("\n");
    res_echte = printf("maar wat doet hij met een dubbele %% en is het resultaat dan nog hetzlefde");
    printf("  res = %d\n", res_echte);
    res_eigen = ft_printf("maar wat doet hij met een dubbele %% en is het resultaat dan nog hetzlefde");
    printf("  res = %d\n", res_eigen);
    ft_printf("\n");
    res_echte = printf("en wat gebeurd er als er een getal: %d van 3 cijfers in staat", 123);
    printf("  res = %d\n", res_echte);
    res_eigen = ft_printf("en wat gebeurd er als er een getal: %d van 3 cijfers in staat", 123);
    printf("  res = %d\n", res_eigen);
    ft_printf("\n");
    res_echte = printf("oke maar lukt het ook met een groot getal met hele gekke paddings zoals [%-20.9d]", 142536);
    printf("  res = %d\n", res_echte);
    res_eigen = ft_printf("oke maar lukt het ook met een groot getal met hele gekke paddings zoals [%-20.9d]", 142536);
    printf("  res = %d\n", res_eigen);
    ft_printf("\n");
    res_echte = printf("en wat gebeurd er als de padding negatief is zoals hier: [%0*d]", -10, 12345);
    printf("  res = %d\n", res_echte);
    res_eigen = ft_printf("en wat gebeurd er als de padding negatief is zoals hier: [%0*d]", -10, 12345);
    printf("  res = %d\n", res_eigen);
    ft_printf("\n");
    printf("echte = [%10x]\n", 703710);
    ft_printf("eigen = [%10x]\n", 703710);
    ft_printf("\n");
    printf("echte = [%-10x]\n", 703710);
    ft_printf("eigen = [%-10x]\n", 703710);
    ft_printf("\n");
    printf("echte = [%10.3x]\n", 703710);
    ft_printf("eigen = [%10.3x]\n", 703710);
    ft_printf("\n");
    printf("echte = [%.10x]\n", 703710);
    ft_printf("eigen = [%.10x]\n", 703710);
    ft_printf("\n");
    printf("echte = [%012.10x]\n", 703710);
    ft_printf("eigen = [%012.10x]\n", 703710);
    ft_printf("\n");
    printf("echte = [%-10x]\n", 703710);
    ft_printf("eigen = [%-10x]\n", 703710);
    ft_printf("\n");
    printf("echte = [%10X]\n", 703710);
    ft_printf("eigen = [%10X]\n", 703710);
    ft_printf("\n");
    printf("echte = [%-10X]\n", 703710);
    ft_printf("eigen = [%-10X]\n", 703710);
    ft_printf("\n");
    printf("echte = [%10.3X]\n", 703710);
    ft_printf("eigen = [%10.3X]\n", 703710);
    ft_printf("\n");
    printf("echte = [%.10X]\n", 703710);
    ft_printf("eigen = [%.10X]\n", 703710);
    ft_printf("\n");
    printf("echte = [%020.10X]\n", 703710);
    ft_printf("eigen = [%020.10X]\n", 703710);
    ft_printf("\n");
    printf("echte = [%-10X]\n", 703710);
    ft_printf("eigen = [%-10X]\n", 703710);
    ft_printf("\n");
    printf("echte = [%X]\n", -703710);
    ft_printf("eigen = [%X]\n", -703710);
    ft_printf("\n");
    printf("echte = [%d]\n", 123);
    ft_printf("eigen = [%d]\n", 123);
    ft_printf("\n");
    printf("echte = [%d]\n", -123); 
    ft_printf("eigen = [%d]\n", -123);
    ft_printf("\n");
    printf("echte = [%.d]\n", 123);
    ft_printf("eigen = [%.d]\n", 123);
    ft_printf("\n");
    printf("echte = [%.6d]\n", -123);
    ft_printf("eigen = [%.6d]\n", -123);
    ft_printf("\n");
    printf("echte = [%010.2d]\n", -123);
    ft_printf("eigen = [%010.2d]\n", -123);
    ft_printf("\n");
    printf("echte = [%10.4d]\n", -123);
    ft_printf("eigen = [%10.4d]\n", -123);
    ft_printf("\n");
    printf("echte = [%-10.4d]\n", -123);
    ft_printf("eigen = [%-10.4d]\n", -123);
    ft_printf("\n");
    printf("echte = [%2d]\n", -123);
    ft_printf("eigen = [%2d]\n", -123);
    ft_printf("\n");
    printf("echte = [%10.5d]\n", 123);
    ft_printf("eigen = [%10.5d]\n", 123);
    ft_printf("\n");
    printf("echte = [%010d]\n", 123);
    ft_printf("eigen = [%010d]\n", 123);
    ft_printf("\n");
    printf("echte = [%*i]\n", 5, 0);
    ft_printf("eigen = [%*i]\n", 5, 0);
    ft_printf("\n");
    printf("echte = [%*i]\n", -5, 0);
    ft_printf("eigen = [%*i]\n", -5, 0);
    ft_printf("\n");
    printf("echte = [%9.2x]\n", 1234);
    ft_printf("eigen = [%9.x]\n", 1234);
    ft_printf("\n");
    printf("echte = [%010.*d]\n", -5, 123);
    ft_printf("eigen = [%010.*d]\n", -5, 123);
    ft_printf("\n");
    printf("echte =  [%-10c]\n", 'a');
    ft_printf("eigen =  [%-10c]\n", 'a');
    ft_printf("\n");
    printf("echte =  [%*c]\n", 10, 'a');
    ft_printf("eigen =  [%*c]\n", 10, 'a');
    ft_printf("\n");
    printf("echte =  [%-*c]\n", 10, 'a');
    ft_printf("eigen =  [%-*c]\n", 10, 'a');
    ft_printf("\n");
    printf("echte =  [%.*s]\n", 10, "abcde");
    ft_printf("eigen =  [%.*s]\n", 10, "abcde");
    ft_printf("\n");
    printf("echte =  [%.*s]\n", 4, "abcde");
    ft_printf("eigen =  [%.*s]\n", 4, "abcde");
    ft_printf("\n");
    printf("echte =  [%*s]\n", 4, "abcde");
    ft_printf("eigen =  [%*s]\n", 4, "abcde");
    ft_printf("\n");
    printf("echte =  [%10s]\n", "abcde");
    ft_printf("eigen =  [%10s]\n", "abcde");
    ft_printf("\n");
    res_echte = printf("de eerste is simpel");
    printf("  res = %d\n", res_echte);
    res_eigen = ft_printf("de eerste is simpel");
    printf("  res = %d\n", res_eigen);
    ft_printf("\n");
    res_echte = printf("Hello, world!");
    printf("  res = %d\n", res_echte);
    res_eigen = ft_printf("Hello, world!");
    printf("  res = %d\n", res_eigen);
    ft_printf("\n");
    res_echte = printf("maar wat doet hij met een dubbele %% en is het resultaat dan nog hetzlefde");
    printf("  res = %d\n", res_echte);
    res_eigen = ft_printf("maar wat doet hij met een dubbele %% en is het resultaat dan nog hetzlefde");
    printf("  res = %d\n", res_eigen);
    ft_printf("\n");
    res_echte = printf("en wat gebeurd er als er een getal: %d van 3 cijfers in staat", 123);
    printf("  res = %d\n", res_echte);
    res_eigen = ft_printf("en wat gebeurd er als er een getal: %d van 3 cijfers in staat", 123);
    printf("  res = %d\n", res_eigen);
    ft_printf("\n");
    res_echte = printf("oke maar lukt het ook met een groot getal met hele gekke paddings zoals [%-20.9d]", 142536);
    printf("  res = %d\n", res_echte);
    res_eigen = ft_printf("oke maar lukt het ook met een groot getal met hele gekke paddings zoals [%-20.9d]", 142536);
    printf("  res = %d\n", res_eigen);
    ft_printf("\n");
    res_echte = printf("en wat gebeurd er als de padding negatief is zoals hier: [%0*d]", -10, 12345);
    printf("  res = %d\n", res_echte);
    res_eigen = ft_printf("en wat gebeurd er als de padding negatief is zoals hier: [%0*d]", -10, 12345);
    printf("  res = %d\n", res_eigen);
    ft_printf("\n");
    printf("echte = [%10x]\n", 703710);
    ft_printf("eigen = [%10x]\n", 703710);
    ft_printf("\n");
    printf("echte = [%-10x]\n", 703710);
    ft_printf("eigen = [%-10x]\n", 703710);
    ft_printf("\n");
    printf("echte = [%10.3x]\n", 703710);
    ft_printf("eigen = [%10.3x]\n", 703710);
    ft_printf("\n");
    printf("echte = [%.10x]\n", 703710);
    ft_printf("eigen = [%.10x]\n", 703710);
    ft_printf("\n");
    printf("echte = [%012.10x]\n", 703710);
    ft_printf("eigen = [%012.10x]\n", 703710);
    ft_printf("\n");
    printf("echte = [%-10x]\n", 703710);
    ft_printf("eigen = [%-10x]\n", 703710);
    ft_printf("\n");
    printf("echte = [%10X]\n", 703710);
    ft_printf("eigen = [%10X]\n", 703710);
    ft_printf("\n");
    printf("echte = [%-10X]\n", 703710);
    ft_printf("eigen = [%-10X]\n", 703710);
    ft_printf("\n");
    printf("echte = [%10.3X]\n", 703710);
    ft_printf("eigen = [%10.3X]\n", 703710);
    ft_printf("\n");
    printf("echte = [%.10X]\n", 703710);
    ft_printf("eigen = [%.10X]\n", 703710);
    ft_printf("\n");
    printf("echte = [%020.10X]\n", 703710);
    ft_printf("eigen = [%020.10X]\n", 703710);
    ft_printf("\n");
    printf("echte = [%-10X]\n", 703710);
    ft_printf("eigen = [%-10X]\n", 703710);
    ft_printf("\n");
    printf("echte = [%d]\n", 123);
    ft_printf("eigen = [%d]\n", 123);
    ft_printf("\n");
    printf("echte = [%d]\n", -123);
    ft_printf("eigen = [%d]\n", -123);
    ft_printf("\n");
    printf("echte = [%.d]\n", 123);
    ft_printf("eigen = [%.d]\n", 123);
    ft_printf("\n");
    printf("echte = [%.6d]\n", -123);
    ft_printf("eigen = [%.6d]\n", -123);
    ft_printf("\n");
    printf("echte = [%010.2d]\n", -123);
    ft_printf("eigen = [%010.2d]\n", -123);
    ft_printf("\n");
    printf("echte = [%10.4d]\n", -123);
    ft_printf("eigen = [%10.4d]\n", -123);
    ft_printf("\n");
    printf("echte = [%-10.4d]\n", -123);
    ft_printf("eigen = [%-10.4d]\n", -123);
    ft_printf("\n");
    printf("echte = [%2d]\n", -123);
    ft_printf("eigen = [%2d]\n", -123);
    ft_printf("\n");
    printf("echte = [%10.5d]\n", 123);
    ft_printf("eigen = [%10.5d]\n", 123);
    ft_printf("\n");
    printf("echte = [%+010d]\n", -123);
    ft_printf("eigen = [%+010d]\n", -123);
    ft_printf("\n");
    printf("echte = [%+010d]\n", -123);
    ft_printf("eigen = [%+010d]\n", -123);
    ft_printf("\n");
    printf("echte = [%*i]\n", 5, 0);
    ft_printf("eigen = [%*i]\n", 5, 0);
    ft_printf("\n");
    printf("echte = [%*i]\n", -5, 0);
    ft_printf("eigen = [%*i]\n", -5, 0);
    ft_printf("\n");
    printf("echte = [%9.2x]\n", 1234);
    ft_printf("eigen = [%9.2x]\n", 1234);
    ft_printf("\n");
    printf("echte = [%010.*d]\n", -5, 123);
    ft_printf("eigen = [%010.*d]\n", -5, 123);
    ft_printf("\n");
    printf("echte = [%-20p]\n", "1234");
    ft_printf("eigen = [%-20p]\n", "1234");
    ft_printf("\n");
    printf("echte = [%20p]\n", "1234");
    ft_printf("eigen = [%20p]\n", "1234");
    ft_printf("\n");
    printf("echte = [%010.*d]\n", -5, 123);
    ft_printf("eigen = [%010.*d]\n", -5, 123);
    return (0);
}
